# Generated by Django 4.2 on 2024-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.CharField(choices=[('everyday', 'Ежедневно'), ('every_week', 'Еженедельно'), ('every_month', 'Ежемесячно')], default='everyday', max_length=80, verbose_name='Периодичность'),
        ),
    ]
