# Generated by Django 4.2 on 2024-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='is_publish',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Не опубликовано')], default=False, verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.BooleanField(choices=[('everyday', 'Ежедневно'), ('every_week', 'Еженедельно')], default='everyday', verbose_name='Периодичность'),
        ),
    ]
