# Generated by Django 4.2 on 2024-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habits_is_publish_alter_habits_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.CharField(choices=[('everyday', 'Ежедневно'), ('every_week', 'Еженедельно')], default='everyday', max_length=80, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='sign_habit',
            field=models.BooleanField(choices=[(True, 'Полезная'), (False, 'Вредная')], verbose_name='Признак приятной привычки'),
        ),
    ]
